sudo: false
language: ruby
cache: bundler
rvm:
- 2.5.1

install:
  # Install Jekyll and dependencies
  - bundle install



script: bundle exec rake site:deploy --quiet #--trace

# Generate your secure token with the travis gem:
# get Github token from your Travis CI profile page
# gem install travis
# GH_TOKEN from https://github.com/settings/tokens
# travis encrypt 'GIT_NAME="YOUR_USERNAME" GIT_EMAIL="YOUR_EMAIL" GH_TOKEN=YOUR_TOKEN'
env:
  global:
    secure: "J2P9z9XCqC3jvoRD+prAWWxf7ACm86JlEJWDrnvqV0zvdjF6vexayfGYg1xrjepppgqhriA+q6XwBGTOAOL6Dg2UyNCgvHFfyNtKVNnc4b/hS8oikOEO88sawYAnBSpNalYfnbbUfp4FnRiF0HbeEXolYxotQtWhwQMLRbod5LBqn5XetD0seivGj7AngmVth/kH9IYqvxpM6FE7p7neAMBto20M4e5y0XDltJDqR7rRkvLsmjFTR/043z/OzpTcCfzbKYeYub4LmAFETGQE46JKBDhaDJlyBmvLwtLbRcaXjjgfNjKWnha+nWcD9xUuEDB/47FVUeDCAiR2nVblxwXavl4f4+E6fAsi69jsZ55f+Z6QtKlNlU7SfiBnGEsBQecoUKtewNtOK5iNDjgoOfieCWwaImhHymcO+a6SLv0hHn+oiBrGp40o7+XDBkeJYQp1Ka14t+Hp4qcdxo6VJ9a1sNpIap5MwHVKPIEVJ+pyH5bZ7s9Cyspn20rKWIE1q0LTrfehgJWLyIzKCTeqTqU4bfIupv5eAGt0Y0F7cPZVSM61qcEIRrSTniThnlrGN7NjBcG5Hk62cb4vadch+V21Qji0vpISnG0R5AO/qTxocpPG92+6OiC7OaZUqmoRDkXiDn8YTYK1YYi8q55+MqusJL4+n2e+hQ32mnhKaKU="
  branches:
  only:
    - master
#changed secure
