sudo: false
language: ruby
cache: bundler
rvm:
- 2.5.1
install:
- bundle install
script: bundle exec rake site:deploy --quiet
env:
  global:
    secure: ERZOAkgMoOa4LNoRZBnnuwxLh2uR0UfZaEfXL/XTdMKO3s5cD2W4x5pkVkh667j65RsxF8EiGLRanANsVnBu4jg7fvVYd5gHH7qIhBTy31mnHj5ghxe64VQFBN2dQT+lmb6uu4gYTvbVxIXPlV313ON5DqDntP0jMqFotWEzC+3+bUP0KgjZMelWAi5rzBEvGuIxwKzEHn0WcrmsOYn3Z6excUYBR4kQipWKjJKDJxKh1EUCE9clEOGf4eopbYuMtT9eHNYAfwsnJ28dhhgdT1V91gfAgO9xtBAtx4fesZK6YDU8T2JL3+AgIuU1+hiKPn3e/Fft9yHs6SVO+rgDuIfjabjnLjEmrjYZnDOMxBjoOs+GpwR4Xmr2QDHPdVVzD4J36kneXx/02ZNFDZ3UcECBJDWFQGkbZTRfXGzQwBLaiI8tFHLE+qFL34PvWTcJbyR2X2AbKCfo2jpvlUfLzPcDjsVjXIkywlVO3YjgJA/sDaqqkUhZhLb3L6LjcoZvABSv5EwgGAGN4c/jeEJyRVCqaAJK91Z2tdhlm5ulJXXNzUpbjnbCurwvOClZTqa90RE14d9nw3o7IN+iVwvWE+AHmhYJWu2pz26zZNHyRh4tXTNlQ4dpHxZ5ZOmGbt8gbJg507Q3hBFMNXB+o1qlY6seugswqGnLYDeq0iVkmmU=
branches:
  only:
  - master
