sudo: false
language: ruby
cache: bundler
rvm:
- 2.5.1

install:
  # Install Jekyll and dependencies
  - bundle install



script: bundle exec rake site:deploy --quiet #--trace

# Generate your secure token with the travis gem:
# get Github token from your Travis CI profile page
# gem install travis
# GH_TOKEN from https://github.com/settings/tokens
# travis encrypt 'GIT_NAME="YOUR_USERNAME" GIT_EMAIL="YOUR_EMAIL" GH_TOKEN=YOUR_TOKEN'
env:
  global:
    secure:="CQGueIEuJCQjueWgXrNQdeuT1/IWx6tGWPhgKGUcAwh4fZ6f7BUf5J/YTZo5Cf8gTgFK4kMABebaHlG1mhY/x8brcshKwlpZEIx/xGLrT/CKRN2z7YSEhngeRbwa+Vuou668I7aDuB5UN/DYGgcMmYN0EkF5ueWR2mwe7xOWqod51HpAchtg6Tw37xfbec80syraS0rp5FdmnLw3EgEZoQgdKW8sc4DpYdckzMYUgrVhDBMsCIfV5cgPLYnQt1QrmpcH0y7jEtP1hbqeUy/Qp6E2sB0lCeP9U634L2YuiqXY3OOqyWvY9yUu9VQqJQikn0Kqp9/wA8svgXEjMcLk5kkNTrZJ9jhnO0+XnUDNEiZ9X54TrbNzY8y5KpLRqHWZowln+Y8iLKT6DJxyiewwZniDuwREbbDOIGkIhEOXEVEfRJk6tWXb+DpkzZu1fCESOj0wbsH16gT8j4bF7MtUjOw4B3K8xmMR9BRGUvO6TGw/CExmNmGKa/9XQkklW22zUXZR60A92z0nJ41jALlmzXxx0vjs/bu1r8K0+eyeEuRK7eGlTW7JqcP/k2HXIwSMl4Om/dsgHgsZihEx+OAWiNClVJm5+mB7nOkxbdj7v636j580xOkd6yTtWUztRqRGv1wdhC3CZkReX/N34zghdtTHCgehgX9Gj7dPfY/3NSc="
branches:
  only:
    - master
#changed secure 20200306
